// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CadastrocentauroTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cadastrocentauro() {
    driver.get("https://www.centauro.com.br/slogin");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.id("username")).sendKeys("t**********s@hotmail.com");
    driver.findElement(By.id("password")).sendKeys("said1998");
    assertThat(driver.findElement(By.cssSelector(".\\_12mr5yh7")).getText(), is("CRIAR UMA CONTA"));
    driver.findElement(By.cssSelector(".\\_12mr5yh7")).click();
    driver.findElement(By.name("Nome")).click();
    driver.findElement(By.name("Nome")).sendKeys("Tonny");
    driver.findElement(By.name("Sobrenome")).click();
    driver.findElement(By.name("Sobrenome")).sendKeys("Said");
    driver.findElement(By.name("CPF")).click();
    driver.findElement(By.name("CPF")).sendKeys("762.335.490-60");
    driver.findElement(By.name("DataDeNascimento")).sendKeys("07/02/1998");
    assertThat(driver.findElement(By.name("Sexo")).getText(), is("Selecione\\\\nMasculino\\\\nFeminino"));
    driver.findElement(By.name("Sexo")).click();
    {
      WebElement dropdown = driver.findElement(By.name("Sexo"));
      dropdown.findElement(By.xpath("//option[. = 'Masculino']")).click();
    }
    driver.findElement(By.name("TelefoneAdicional")).click();
    driver.findElement(By.name("TelefoneAdicional")).sendKeys("(81) 98862-9093");
    driver.findElement(By.name("Email")).click();
    driver.findElement(By.name("Email")).sendKeys("ramil1678@uorak.com");
    driver.findElement(By.name("Senha")).sendKeys("bolo123");
    driver.findElement(By.name("ConfirmacaoSenha")).sendKeys("bolo123");
    driver.findElement(By.name("CEP")).sendKeys("02281-229");
    driver.findElement(By.cssSelector("#newsletter > .\\_15def4c")).click();
    driver.findElement(By.name("Numero")).sendKeys("111");
    driver.findElement(By.cssSelector("#terms-accept > .\\_15def4c")).click();
    driver.findElement(By.cssSelector(".\\_159r3op8")).click();
  }
}
